[general]
domain = "0.0.0.0"
port = 8643
interval = "5s"

[log]
level = "debug"

[tls]
cert_path = "./dev/cert/localhost.crt"
skey_path = "./dev/cert/localhost.key"

[database.postgres]
name = "evdp"
port = 5432
username = "guest"
tls_mode = "disable" # 'enable' is not implemented

[coingecko]
update_list_interval = "1h"
